/** Locked scaffold files — AI never overwrites these paths. */

export const SCAFFOLD_PATHS = [
  'package.json',
  'vite.config.js',
  'index.html',
  'src/main.jsx',
  'src/index.css',
];

export function scaffoldPackageJson() {
  return JSON.stringify(
    {
      name: 'design-agent-app',
      private: true,
      version: '0.0.0',
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'vite build',
        preview: 'vite preview',
      },
      dependencies: {
        react: '^18.3.1',
        'react-dom': '^18.3.1',
      },
      devDependencies: {
        '@vitejs/plugin-react': '^4.3.4',
        vite: '^6.0.6',
      },
    },
    null,
    2
  );
}

export function scaffoldViteConfig() {
  return `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
`;
}

export function scaffoldIndexHtml() {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Design Agent App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;
}

export function scaffoldMainJsx() {
  return `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './app/App.jsx';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;
}

export function scaffoldIndexCss() {
  return `*, *::before, *::after { box-sizing: border-box; }
html, body, #root { margin: 0; min-height: 100%; }
body { font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
`;
}

export function scaffoldReadme(projectName = 'Design Agent App') {
  return `# ${projectName}

Frontend React app generated by **PM Agent Design Agent**.

## Quick start

\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:5173

## Project structure

- \`src/app/\` — React components, pages, and App shell
- \`src/styles/\` — design tokens and global CSS
- \`package.json\`, \`vite.config.js\`, \`index.html\` — standard Vite + React 18 scaffold

Share this repo with your backend developer as the UI frontend.
`;
}

export function getScaffoldFiles(projectName = 'Design Agent App') {
  return {
    'package.json': scaffoldPackageJson(),
    'vite.config.js': scaffoldViteConfig(),
    'index.html': scaffoldIndexHtml(),
    'src/main.jsx': scaffoldMainJsx(),
    'src/index.css': scaffoldIndexCss(),
    'README.md': scaffoldReadme(projectName),
    '.gitignore': 'node_modules\ndist\n.DS_Store\n*.local\n',
  };
}

const LOCKED = new Set(SCAFFOLD_PATHS);

/** Merge AI-generated files with locked scaffold. AI paths under src/app/ only. */
export function buildFullProject(aiFiles = {}, projectName = 'Design Agent App') {
  const scaffold = getScaffoldFiles(projectName);
  const merged = { ...scaffold };

  for (const [path, content] of Object.entries(aiFiles)) {
    const normalized = path.replace(/^\/+/, '');
    if (LOCKED.has(normalized)) continue;
    if (typeof content === 'string' && content.trim()) {
      merged[normalized] = content;
    }
  }

  if (!merged['src/app/App.jsx']) {
    throw new Error('AI output must include src/app/App.jsx');
  }

  if (!merged['src/styles/tokens.css']) {
    merged['src/styles/tokens.css'] = `:root {
  --bg: #f8fafc;
  --surface: #fff;
  --text: #0f172a;
  --muted: #64748b;
  --accent: #6366f1;
}\n`;
  }
  if (!merged['src/styles/global.css']) {
    merged['src/styles/global.css'] = `@import './tokens.css';\n`;
  }

  return merged;
}

export function parseAiProjectResponse(raw) {
  let text = (raw || '').trim();
  if (!text) throw new Error('Empty AI response');

  const fence = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fence) text = fence[1].trim();

  const parsed = JSON.parse(text);
  const files = parsed.files || parsed;
  if (!files || typeof files !== 'object' || Array.isArray(files)) {
    throw new Error('AI response missing files object');
  }

  const normalized = {};
  for (const [path, content] of Object.entries(files)) {
    if (typeof content !== 'string') continue;
    normalized[path.replace(/^\/+/, '')] = content;
  }

  return {
    files: normalized,
    entry: (parsed.entry || 'src/app/App.jsx').replace(/^\/+/, ''),
    description: parsed.description || '',
  };
}
